-- AlterTable
ALTER TABLE "Usuario" ALTER COLUMN "nome" DROP NOT NULL,
ALTER COLUMN "email" DROP NOT NULL,
ALTER COLUMN "senha" DROP NOT NULL,
ALTER COLUMN "telefone" DROP NOT NULL,
ALTER COLUMN "data de criacao" DROP NOT NULL,
ALTER COLUMN "data de atualizacao" DROP NOT NULL,
ALTER COLUMN "role" DROP NOT NULL;

-- AlterTable
ALTER TABLE "itens" ALTER COLUMN "nome" DROP NOT NULL;
